### ISSUE TITLE
[Suggestion] Lists and Libraries: include new action buttons

### ISSUE THREAD

**Issue by spcfran** [DariuS231/ChromeSPDevTools#18]
The Lists and Libraries module provides links to SP pages for list settings and permissions which cover many of the operations one would want to do with a list.

However there are some actions not available on the UI but there's an API in JSOM / REST for it, for example hide/unhide a list. It would be great to have some of these actions inline on the tool itself.

**Comment by DariuS231** [comment]
That sounds like a very useful option, I'm think it might be a good idea to add some sort of contextual menu with all the option available so far and the ones to come.

[http://dev.office.com/fabric#/components/contextualmenu](http://dev.office.com/fabric#/components/contextualmenu)

I'm thinking about adding the delete option as well.

**Comment by DariuS231** [comment]
@jquintozamora is thinking about it. No pressure :)
