### ISSUE TITLE
Support for SharePoint 2010

### ISSUE THREAD

**Issue by wiliammbr** [DariuS231/ChromeSPDevTools#21]
First, I would like to say that this Chrome extension is awesome! It has a lot of potential and the way it is currently will help my productivity a lot.

Anyway, I would like to ask if you could remove the "15/" from URL constants since SharePoint redirects automatically to the correct location or perhaps, check the _spPageContextInfo.webUIVersion for SharePoint 2010 support. We have a few SharePoint 2010 websites running and I would like to use your extension there too.

**Comment by DariuS231** [comment]
I'm Happy you find it useful. 

About the request, I can remove the 15 prefix from the URL but  you might find other issues,  as in some actions I'm using rest Apis which I don't remember being available in 2010 and sadly, I haven't got a 2010 environment to test the app. 

If you have a 2010 environment to test the extension, you are more than welcome to collaborate with the tool!

**Comment by DariuS231** [comment]
@wiliammbr, Just to let you know that I made the changes and should be publishing a new version next week.

**Comment by wiliammbr** [comment]
@DariuS231 Thanks for the attention, I'm looking forward on updating the extension!
As soon as I get more free time next week, I'm planning to test more on 2010 environments to keep improving it.

**Comment by DariuS231** [comment]
@wiliammbr, I managed to get a testing environment and sadly a bigger change was required to give support to SP 2010. In fact, getting rid of the 15 prefix, affected some functionality already working on SP 2013 and Online.
